import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const projectRoot = resolve(import.meta.dirname, '..')

describe('browser demo', () => {
  it('documents and exercises the Vue demo app', async () => {
    const [demoHtml, appVue, composable, readme, packageJson] = await Promise.all([
      readFile(resolve(projectRoot, 'demo/index.html'), 'utf8'),
      readFile(resolve(projectRoot, 'demo/App.vue'), 'utf8'),
      readFile(resolve(projectRoot, 'demo/composables/use-gaudio-demo.ts'), 'utf8'),
      readFile(resolve(projectRoot, 'README.md'), 'utf8'),
      readFile(resolve(projectRoot, 'package.json'), 'utf8'),
    ])

    expect(demoHtml).toContain('/main.ts')
    expect(appVue).toContain('useGaudioDemo')
    expect(composable).toContain('new AudioPlayer')
    expect(composable).toContain('from \'gaudio/hls\'')
    expect(composable).toContain('from \'gaudio/dash\'')
    expect(composable).toContain('createHlsAdapter')
    expect(composable).toContain('createDashAdapter')
    expect(composable).toContain('protocolOverride')
    expect(composable).toContain('player.on(\'adaptivechange\'')
    expect(composable).toContain('player.on(\'manifestloaded\'')
    expect(composable).toContain('player.on(\'variantchange\'')
    expect(composable).toContain('player.on(\'segmentloaded\'')
    expect(composable).toContain('player.on(\'streamerror\'')
    expect(composable).toContain('defaultDemoSampleUrl')
    expect(composable).toContain('selectTrack')
    expect(composable).toContain('selectFormat')
    expect(composable).toContain('player.on(\'seeking\'')
    expect(composable).toContain('setMuted')
    expect(composable).toContain('setLoop')
    expect(composable).toContain('setPreload')
    expect(composable).toContain('fastSeek')
    expect(composable).toContain('setAutoplay')
    expect(composable).toContain('setPreservesPitch')
    expect(composable).toContain('getPlayedRanges')
    expect(appVue).toContain('selectFormat')
    expect(appVue).toContain('selectTrack')
    expect(appVue).toContain('Muted')
    expect(appVue).toContain('Loop')
    expect(appVue).toContain('Preload')
    expect(appVue).toContain('Fast seek')
    expect(appVue).toContain('Autoplay')
    expect(appVue).toContain('Preserve pitch')
    expect(appVue).toContain('Played')
    expect(appVue).toContain('Seeking')
    expect(appVue).toContain('Protocol')
    expect(appVue).toContain('Implementation')
    expect(appVue).toContain('Variant')
    expect(appVue).toContain('Bitrate')
    expect(appVue).toContain('Segment')
    expect(readme).toContain('pnpm run demo')
    expect(readme).toContain('Migration from 0.1.0')
    expect(readme).toContain('Migration from 0.2.0')
    expect(readme).toContain('autoplay')
    expect(readme).toContain('fastSeek')
    expect(readme).toContain('preservesPitch')
    expect(readme).toContain('getPlayedRanges')
    expect(readme).toContain('from \'gaudio/hls\'')
    expect(readme).toContain('from \'gaudio/dash\'')
    expect(readme).toContain('native-first')
    expect(readme).toContain('updateConfig')
    expect(readme).toContain('updateSettings')
    expect(readme).toContain('Migration from 0.3.0')
    expect(packageJson).toContain('"demo"')
    expect(packageJson).toContain('"demo:build"')
    expect(packageJson).toContain('"version": "0.4.0"')
    expect(packageJson).toContain('vite')
    expect(packageJson).toContain('vue')
  })
})
